### ISSUE TITLE
x-api-key 401 error

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/rest-api#190]
When passing a x-api-key a 401 error is returned attempting to obtain zones: GET https://swissre.placeos.powerworkplace.com/api/engine/v2/zones?tags=org net::ERR_ABORTED 401

**Comment by stakach** [comment]
fixed in https://github.com/PlaceOS/rest-api/commit/f3f18de6c9a56af045d2673c36f1ab7355b68699
@MrYuion the issue was that the API key is never returned to the frontend

on create you'll see this field: `x_api_key` which will be a String on creation.
![image](https://user-images.githubusercontent.com/368013/135029667-9da70794-793a-4356-ac83-946d976c1837.png)

**Comment by caspiano** [comment]
Closed by #193
